onlyBuiltDependencies:
  - sharp
  - unrs-resolver

minimunReleaseAge: 2880 # 2 days

allowBuilds:
  '@clerk/shared': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
